# Generated by Django 3.1.7 on 2021-07-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signuptask', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instruction',
            new_name='user_info',
        ),
    ]
