# Generated by Django 3.1.7 on 2021-07-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signuptask', '0002_auto_20210719_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='password1',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
