# Generated by Django 3.1.7 on 2021-07-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signuptask', '0005_auto_20210719_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
